### ISSUE TITLE
Handle CVRs that encode overvotes

### ISSUE THREAD

**Issue by danwallach** [votingworks/arlo-e2e#17]
Right now, we're assuming that every ballot in the CVR is "well-formed", i.e., no overvotes. It's entirely possible that we're given a ballot that has an overvote in it. What are we supposed to do?

- If we see an overvote in any contest, we should encrypt all zeros for the selections, such that the homomorphic tallies for that contest come out correct.
- We should separately generate some feedback about how many overvotes showed up in the input and what we did with them.

**Comment by benadida** [comment]
For now, let's encode overvotes as blanks. Once EG has support for overvotes, we can choose to move to that.

**Comment by benadida** [comment]
waiting for scalability to get to this.
